#!/bin/bash
# ==========================================
# Database Setup Script
# ==========================================
# Purpose: Initialize PostgreSQL database for crypto trading bot
# Usage: ./setup_database.sh [postgres_user] [postgres_password]
# ==========================================

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
DB_USER="${1:-postgres}"
DB_PASSWORD="${2:-}"
DB_NAME="crypto_trading_bot"
DB_HOST="${DB_HOST:-localhost}"
DB_PORT="${DB_PORT:-5432}"

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
MIGRATIONS_DIR="${PROJECT_ROOT}/database/migrations"

echo -e "${BLUE}===========================================${NC}"
echo -e "${BLUE}Crypto Trading Bot - Database Setup${NC}"
echo -e "${BLUE}===========================================${NC}"
echo ""

# Function to print status
print_status() {
    echo -e "${BLUE}==>${NC} $1"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

# Check if PostgreSQL is running
print_status "Checking PostgreSQL connection..."
if pg_isready -h $DB_HOST -p $DB_PORT >/dev/null 2>&1; then
    print_success "PostgreSQL is running on ${DB_HOST}:${DB_PORT}"
else
    print_error "PostgreSQL is not running on ${DB_HOST}:${DB_PORT}"
    print_warning "Please start PostgreSQL and try again"
    exit 1
fi

# Check if psql is installed
if ! command -v psql &> /dev/null; then
    print_error "psql command not found"
    print_warning "Please install PostgreSQL client tools"
    exit 1
fi

# Set password if provided
if [ -n "$DB_PASSWORD" ]; then
    export PGPASSWORD="$DB_PASSWORD"
fi

# Create database if it doesn't exist
print_status "Creating database '$DB_NAME'..."
psql -h $DB_HOST -p $DB_PORT -U $DB_USER -tc "SELECT 1 FROM pg_database WHERE datname = '$DB_NAME'" | grep -q 1 || \
psql -h $DB_HOST -p $DB_PORT -U $DB_USER -c "CREATE DATABASE $DB_NAME"

if [ $? -eq 0 ]; then
    print_success "Database '$DB_NAME' created or already exists"
else
    print_error "Failed to create database"
    exit 1
fi

# Run migrations in order
print_status "Running database migrations..."

for migration in $MIGRATIONS_DIR/*.sql; do
    migration_name=$(basename $migration)
    print_status "Applying migration: $migration_name"

    if psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -f "$migration" > /dev/null 2>&1; then
        print_success "Migration $migration_name completed"
    else
        # Try again with verbose output
        print_warning "Migration $migration_name may have warnings, checking..."
        psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -f "$migration"
        if [ $? -eq 0 ]; then
            print_success "Migration $migration_name completed with warnings"
        else
            print_error "Migration $migration_name failed"
            exit 1
        fi
    fi
done

# Verify setup
print_status "Verifying database setup..."

# Check if tables exist
TABLE_COUNT=$(psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -tAc \
    "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public'")

if [ "$TABLE_COUNT" -gt 0 ]; then
    print_success "Found $TABLE_COUNT tables in database"
else
    print_error "No tables found in database"
    exit 1
fi

# Check if default portfolio exists
PORTFOLIO_EXISTS=$(psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -tAc \
    "SELECT COUNT(*) FROM portfolios WHERE portfolio_id = 'default'")

if [ "$PORTFOLIO_EXISTS" -eq 1 ]; then
    print_success "Default portfolio created"
else
    print_warning "Default portfolio not found"
fi

# Create .env file for database connection
print_status "Creating database configuration file..."

ENV_FILE="${PROJECT_ROOT}/database/.env"
cat > "$ENV_FILE" << EOF
# Database Configuration
# Auto-generated by setup_database.sh on $(date)

DB_HOST=$DB_HOST
DB_PORT=$DB_PORT
DB_NAME=$DB_NAME
DB_USER=$DB_USER
DB_PASSWORD=$DB_PASSWORD

# Connection string for SQLAlchemy
DATABASE_URL=postgresql://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME

# Connection pool settings
DB_POOL_SIZE=20
DB_MAX_OVERFLOW=40
DB_POOL_TIMEOUT=30
DB_POOL_RECYCLE=3600
EOF

print_success "Database configuration saved to $ENV_FILE"

# Display connection info
echo ""
echo -e "${GREEN}===========================================${NC}"
echo -e "${GREEN}Database Setup Complete!${NC}"
echo -e "${GREEN}===========================================${NC}"
echo ""
echo -e "${BLUE}Connection Details:${NC}"
echo -e "  Host:     $DB_HOST"
echo -e "  Port:     $DB_PORT"
echo -e "  Database: $DB_NAME"
echo -e "  User:     $DB_USER"
echo ""
echo -e "${BLUE}Tables Created:${NC} $TABLE_COUNT"
echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo -e "  1. Update your service .env files to use the database"
echo -e "  2. Source: ${ENV_FILE}"
echo -e "  3. Test connection with: psql -h $DB_HOST -U $DB_USER -d $DB_NAME"
echo ""

# Show table list
echo -e "${BLUE}Tables in database:${NC}"
psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -c "\dt" | grep -v "Did not find" || true

# Unset password
unset PGPASSWORD
