#!/usr/bin/env bash
#
# ============================================================================
# UNREVIEWED — DO NOT RUN WITHOUT OPERATOR APPROVAL.
# Generated by doc-triage pass 2026-08-03. This script has NOT been executed.
# It moves files (git mv, history-preserving) into docs/archive/2026-08-03/<path>.
# It NEVER deletes anything. Read .planning/audits/2026-08-03-doc-triage.md first.
# One commit per batch, file list in the commit body, per project convention.
# ============================================================================
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"
DEST_BASE="docs/archive/2026-08-03"

move_batch() {
  # $1 = destination subdir under DEST_BASE, remaining args = source paths
  local dest_root="$1"; shift
  for f in "$@"; do
    mkdir -p "$DEST_BASE/$(dirname "$f")"
    git mv "$f" "$DEST_BASE/$f"
  done
}

# ----------------------------------------------------------------------------
# Batch 1 — root (2 files): dated one-off audit + fixes reports, superseded
# by .planning/audits/* and wiki ADRs. Root goes from 6 -> 4 tracked .md files.
# ----------------------------------------------------------------------------
move_batch root \
  "AUDIT_2026-07-29_PRODUCTION_REVIEW.md" \
  "FIXES_2026-07-28_COMPREHENSIVE.md"

git commit -m "$(cat <<'EOF'
docs(archive): move dated root audit/fixes reports to docs/archive/2026-08-03

Root .md count reduced to the 4 living files (README, CLAUDE, RUNBOOK,
progress). Both moved files are superseded by later ADRs and
.planning/audits/*.

Files (2):
- AUDIT_2026-07-29_PRODUCTION_REVIEW.md
- FIXES_2026-07-28_COMPREHENSIVE.md
EOF
)"

# ----------------------------------------------------------------------------
# Batch 2 — docs/strategy/ (22 files) + docs/ml/ML_DATA_COLLECTION_GUIDE.md
# (23 files). Dated research folders, orphaned (nothing in wiki/ links to
# docs/strategy/), superseded by wiki/decisions/ADR-013-strategy-rebuild-plan.md
# and wiki/concepts/ML-Status.md.
# ----------------------------------------------------------------------------
move_batch docs \
  "docs/strategy/RESEARCH_PLAN_2026-04-29.md" \
  "docs/strategy/evidence/phase_b_walkforward_ensemble_2026-05-20.md" \
  "docs/strategy/evidence/phase_c_results_2026-05-06.md" \
  "docs/strategy/research-2026-04-29/01-crypto-factors.md" \
  "docs/strategy/research-2026-04-29/02-indicator-ml-hybrid.md" \
  "docs/strategy/research-2026-04-29/03-risk-management-overlays.md" \
  "docs/strategy/research-2026-04-29/04-equity-to-crypto-failure-modes.md" \
  "docs/strategy/research-2026-04-29/05-retail-practitioners.md" \
  "docs/strategy/research-2026-04-29/06-execution-sizing.md" \
  "docs/strategy/research-2026-04-29/T0.1-gru-rebuild-design.md" \
  "docs/strategy/research-2026-04-29/T0.1-rebuild-decision.md" \
  "docs/strategy/research-2026-04-29/T0.1-rebuild-results.md" \
  "docs/strategy/research-2026-04-29/T0.2-cpcv-design.md" \
  "docs/strategy/research-2026-04-29/T1.2-design.md" \
  "docs/strategy/research-2026-04-29/T1.2-vol-parity-paper-test-runbook.md" \
  "docs/strategy/research-2026-04-29/V0-FINDINGS-gru-metric-bug.md" \
  "docs/strategy/research-2026-04-29/V0-RESULTS-no-edge.md" \
  "docs/strategy/research-2026-05-21/C2-wrap-decision-rules.md" \
  "docs/strategy/research-2026-05-21/T0.1-rebuild-results.md" \
  "docs/strategy/research-2026-05-21/horizon-1D/T0.1-rebuild-results.md" \
  "docs/strategy/research-2026-05-21/horizon-4H/T0.1-rebuild-results.md" \
  "docs/strategy/research-2026-05-21/horizon-4H-fresh/T0.1-rebuild-results.md" \
  "docs/ml/ML_DATA_COLLECTION_GUIDE.md"

git commit -m "$(cat <<'EOF'
docs(archive): move superseded strategy-research tree to docs/archive/2026-08-03

docs/strategy/ (research-2026-04-29, research-2026-05-21, evidence/,
RESEARCH_PLAN_2026-04-29.md) is orphaned -- nothing in wiki/ links to it --
and superseded by wiki/decisions/ADR-013-strategy-rebuild-plan.md.
docs/ml/ML_DATA_COLLECTION_GUIDE.md predates the GRU rebuild and is
superseded by wiki/concepts/ML-Status.md.

Files (23): see docs/strategy/** and docs/ml/ML_DATA_COLLECTION_GUIDE.md
listed in .planning/audits/2026-08-03-doc-triage.md
EOF
)"

# ----------------------------------------------------------------------------
# Batch 3 — services/ml-prediction-service (4 files): describe removed LSTM
# as a live, selectable model. predictor_factory.py:25-26 raises ValueError
# for LSTM; main.py:1386-1392 returns "LSTM training removed". P1 contradiction.
# ----------------------------------------------------------------------------
move_batch services \
  "services/ml-prediction-service/docs/ENSEMBLE_PREDICTIONS.md" \
  "services/ml-prediction-service/docs/GRU_IMPLEMENTATION_SUMMARY.md" \
  "services/ml-prediction-service/docs/GRU_MODEL.md" \
  "services/ml-prediction-service/tests/README.md"

git commit -m "$(cat <<'EOF'
docs(archive): move ml-prediction-service LSTM docs to docs/archive/2026-08-03

These describe LSTM as a live, trainable, selectable model with working
API examples. predictor_factory.py:25-26 raises ValueError for LSTM;
main.py:1386-1392 returns "LSTM training removed" on the training endpoint.
See P1 row in .planning/audits/2026-08-03-doc-triage.md.

Files (4):
- services/ml-prediction-service/docs/ENSEMBLE_PREDICTIONS.md
- services/ml-prediction-service/docs/GRU_IMPLEMENTATION_SUMMARY.md
- services/ml-prediction-service/docs/GRU_MODEL.md
- services/ml-prediction-service/tests/README.md
EOF
)"

# ----------------------------------------------------------------------------
# Batch 4 — services/trading-engine + services/technical-analysis (12 files):
# stale $10,000-account guides (P0), a false "slippage considered" claim (P0),
# and dated Nov-2025 completion/backtest reports (some doubly invalid --
# pre-2026-04-25 testnet/mainnet contamination).
# ----------------------------------------------------------------------------
move_batch services \
  "services/trading-engine/DEPLOYMENT_CHECKLIST.md" \
  "services/trading-engine/MULTI_SYMBOL_PORTFOLIO_GUIDE.md" \
  "services/trading-engine/POSITION_SIZING_GUIDE.md" \
  "services/trading-engine/docs/AUTOMATED_TESTING_SUMMARY.md" \
  "services/trading-engine/tests/integration/DATABASE_PERSISTENCE_TESTS_IMPLEMENTATION.md" \
  "services/trading-engine/tests/integration/INTEGRATION_TEST_REPORT.md" \
  "services/technical-analysis/backtesting/BACKTEST_IMPLEMENTATION_COMPLETE.md" \
  "services/technical-analysis/backtesting/BTC_ETH_REAL_DATA_ANALYSIS.md" \
  "services/technical-analysis/backtesting/DELIVERY_SUMMARY.md" \
  "services/technical-analysis/backtesting/OPTION_C_IMPLEMENTATION.md" \
  "services/technical-analysis/backtesting/PARAMETER_OPTIMIZATION_DELIVERY.md" \
  "services/technical-analysis/backtesting/SQZMOM_BACKTEST_REPORT.md"

git commit -m "$(cat <<'EOF'
docs(archive): move stale trading-engine/technical-analysis reports to docs/archive/2026-08-03

MULTI_SYMBOL_PORTFOLIO_GUIDE.md and POSITION_SIZING_GUIDE.md assume a
$10,000 account (real default is $100, shared/account.py) and the former
falsely claims paper trading models slippage (paper_trading.py fills at
current_price with no slippage adjustment). DEPLOYMENT_CHECKLIST.md is
self-annotated historical, superseded by RUNBOOK.md's Pre-LIVE checklist.
The technical-analysis backtesting reports are dated Nov 2025 completion/
result summaries, several pre-dating the 2026-04-25 testnet/mainnet
contamination cutoff (OPTION_C_IMPLEMENTATION.md additionally claims
DOGEUSDT as a "profitable symbol" -- DOGEUSDT is excluded from validated
symbols per CLAUDE.md). See P0 rows in .planning/audits/2026-08-03-doc-triage.md.

Files (12): see services/trading-engine/** and
services/technical-analysis/backtesting/** listed in the triage report.
EOF
)"

# ----------------------------------------------------------------------------
# Batch 5 — reports/ (10 files, entire directory): individually dated
# scheduled-task output snapshots (edge-audits, premarket, runtime-checks,
# walk-forward). The living how-to guides for this system
# (docs/operations/PERFORMANCE_REPORTING.md etc.) are unaffected.
# ----------------------------------------------------------------------------
move_batch reports \
  "reports/edge-audits/2026-W19.md" \
  "reports/edge-audits/2026-W21.md" \
  "reports/premarket/2026-05-08.md" \
  "reports/premarket/2026-05-19.md" \
  "reports/premarket/2026-05-20.md" \
  "reports/runtime-checks/2026-05-08.md" \
  "reports/runtime-checks/2026-05-09.md" \
  "reports/runtime-checks/2026-05-19.md" \
  "reports/runtime-checks/2026-05-20.md" \
  "reports/walk-forward/2026-05-19.md"

git commit -m "$(cat <<'EOF'
docs(archive): move dated reports/ snapshots to docs/archive/2026-08-03

reports/ contains individually dated scheduled-task output (edge-audits,
premarket checks, runtime-checks, walk-forward) -- one-off status snapshots,
not living documentation. The how-to guides for the reporting system itself
(docs/operations/PERFORMANCE_REPORTING.md, WEEKLY_REPORT_INDEX.md,
WEEKLY_REPORT_QUICK_START.md) are untouched.

Files (10): entire reports/ tree, listed in
.planning/audits/2026-08-03-doc-triage.md
EOF
)"

# ----------------------------------------------------------------------------
# Batch 6 — infrastructure/ (2 files) + .github/ (2 files): dated completion
# reports superseded by living README/security docs.
# ----------------------------------------------------------------------------
move_batch infra-cicd \
  "infrastructure/kubernetes/staging/DEPLOYMENT_REPORT.md" \
  "infrastructure/kubernetes/security/SECURITY_CONFIGURATION_SUMMARY.md" \
  ".github/CICD_IMPLEMENTATION_REPORT.md" \
  ".github/CICD_SUMMARY.md"

git commit -m "$(cat <<'EOF'
docs(archive): move dated infra/CI-CD completion reports to docs/archive/2026-08-03

infrastructure/kubernetes/staging/DEPLOYMENT_REPORT.md and
kubernetes/security/SECURITY_CONFIGURATION_SUMMARY.md are one-off
Dec-2025 summaries superseded by the living README/security docs in the
same directories. .github/CICD_IMPLEMENTATION_REPORT.md and CICD_SUMMARY.md
are Nov-2025 completion reports redundant with the living
.github/CICD_README.md.

Files (4):
- infrastructure/kubernetes/staging/DEPLOYMENT_REPORT.md
- infrastructure/kubernetes/security/SECURITY_CONFIGURATION_SUMMARY.md
- .github/CICD_IMPLEMENTATION_REPORT.md
- .github/CICD_SUMMARY.md
EOF
)"

# ----------------------------------------------------------------------------
# Batch 7 — backtesting/backtesting/results/ (6 files, entire results dir):
# dated 2025-11-14/16, pre-2026-04-25 testnet/mainnet contamination cutoff --
# doubly invalid as evidence. backtesting/README.md (the how-to) is untouched.
# ----------------------------------------------------------------------------
move_batch backtesting \
  "backtesting/backtesting/results/BACKTEST_COMPARISON_BTCUSDT_60m_10d_20251116_214326.md" \
  "backtesting/backtesting/results/BACKTEST_COMPARISON_BTCUSDT_60m_30d_20251114_141237.md" \
  "backtesting/backtesting/results/BACKTEST_COMPARISON_BTCUSDT_60m_30d_20251114_142447.md" \
  "backtesting/backtesting/results/BACKTEST_COMPARISON_SUMMARY_20251114_141237.md" \
  "backtesting/backtesting/results/BACKTEST_COMPARISON_SUMMARY_20251114_142447.md" \
  "backtesting/backtesting/results/BACKTEST_COMPARISON_SUMMARY_20251116_214326.md"

git commit -m "$(cat <<'EOF'
docs(archive): move dated backtest result snapshots to docs/archive/2026-08-03

All six files are dated 2025-11-14/16, predating the 2026-04-25
testnet/mainnet contamination cutoff -- stale AND contaminated as evidence.
backtesting/README.md (the module how-to) is untouched.

Files (6): entire backtesting/backtesting/results/ tree, listed in
.planning/audits/2026-08-03-doc-triage.md
EOF
)"

# ----------------------------------------------------------------------------
# Batch 8 — wiki/.raw/agent-reports/ (11 files) + wiki/meta/lint-report-2026-05-06.md
# (1 file). NOT wiki/decisions/ -- ADR home is untouched. These are raw
# ingestion inputs, superseded by the distilled wiki/modules/*.md pages, and
# a superseded lint snapshot (newer one at lint-report-2026-07-30.md kept).
# ----------------------------------------------------------------------------
move_batch wiki \
  "wiki/.raw/agent-reports/api-gateway.md" \
  "wiki/.raw/agent-reports/bybit-connector.md" \
  "wiki/.raw/agent-reports/market-data-service.md" \
  "wiki/.raw/agent-reports/ml-prediction-service.md" \
  "wiki/.raw/agent-reports/ml-retraining-service.md" \
  "wiki/.raw/agent-reports/notification-service.md" \
  "wiki/.raw/agent-reports/portfolio-manager.md" \
  "wiki/.raw/agent-reports/risk-metrics-service.md" \
  "wiki/.raw/agent-reports/sentiment-analysis-service.md" \
  "wiki/.raw/agent-reports/technical-analysis.md" \
  "wiki/.raw/agent-reports/trading-engine.md" \
  "wiki/meta/lint-report-2026-05-06.md"

git commit -m "$(cat <<'EOF'
docs(archive): move raw wiki ingestion inputs to docs/archive/2026-08-03

wiki/decisions/ (the ADR home) is untouched. wiki/.raw/agent-reports/* are
Stage-1 code-mapping agent outputs, superseded by the distilled
wiki/modules/*.md pages that cite them. wiki/meta/lint-report-2026-05-06.md
is superseded by the newer wiki/meta/lint-report-2026-07-30.md.

Files (12):
- wiki/.raw/agent-reports/*.md (11 files)
- wiki/meta/lint-report-2026-05-06.md
EOF
)"

echo "All 8 batches applied (73 files). Review with: git log --stat -8"

# ============================================================================
# NOT INCLUDED ABOVE, ON PURPOSE -- .planning/ milestone cleanup
# ============================================================================
# The v1.0/v1.1/v1.2 completed-milestone trees under .planning/milestones/
# (MILESTONE-AUDIT.md, REQUIREMENTS.md, ROADMAP.md, *-phases/) look like
# ARCHIVE candidates by content (~150+ files), but .planning/ is live GSD
# framework state with path-resolution expectations this triage did not
# verify. Left UNCLASSIFIED and UNMOVED. Do not run the block below without
# explicit operator sign-off AND confirming the GSD framework tolerates the
# move (check .claude/get-shit-done/ path assumptions first).
#
# move_batch planning-completed-milestones \
#   ".planning/milestones/v1.0-MILESTONE-AUDIT.md" \
#   ".planning/milestones/v1.0-REQUIREMENTS.md" \
#   ".planning/milestones/v1.0-ROADMAP.md" \
#   ".planning/milestones/v1.1-MILESTONE-AUDIT.md" \
#   ".planning/milestones/v1.1-REQUIREMENTS.md" \
#   ".planning/milestones/v1.1-ROADMAP.md" \
#   ".planning/milestones/v1.2-MILESTONE-AUDIT.md" \
#   ".planning/milestones/v1.2-REQUIREMENTS.md" \
#   ".planning/milestones/v1.2-ROADMAP.md"
#   # plus the entire v1.0-phases/, v1.1-phases/, v1.2-phases/ trees --
#   # not enumerated here; do a fresh listing before ever running this.
