"""
Strategy Base Class for Backtesting Framework
Defines the interface that all trading strategies must implement.
"""

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime
from enum import Enum

logger = logging.getLogger(__name__)


class SignalType(Enum):
    """Trading signal types"""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    CLOSE_LONG = "close_long"
    CLOSE_SHORT = "close_short"


@dataclass
class Signal:
    """
    Trading signal generated by a strategy

    Attributes:
        signal_type: Type of signal (BUY, SELL, HOLD, etc.)
        symbol: Trading pair symbol
        price: Current price when signal was generated
        timestamp: When signal was generated
        confidence: Signal confidence (0.0-1.0)
        stop_loss: Suggested stop loss price
        take_profit: Suggested take profit price
        position_size_pct: Suggested position size as % of equity
        metadata: Additional signal metadata
    """
    signal_type: SignalType
    symbol: str
    price: float
    timestamp: datetime
    confidence: float = 0.5
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    position_size_pct: float = 1.0  # 100% of calculated size
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "signal_type": self.signal_type.value,
            "symbol": self.symbol,
            "price": self.price,
            "timestamp": self.timestamp.isoformat(),
            "confidence": self.confidence,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "position_size_pct": self.position_size_pct,
            "metadata": self.metadata
        }


@dataclass
class OHLCV:
    """Single OHLCV bar"""
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float

    def to_dict(self) -> Dict[str, Any]:
        return {
            "timestamp": self.timestamp.isoformat(),
            "open": self.open,
            "high": self.high,
            "low": self.low,
            "close": self.close,
            "volume": self.volume
        }


class StrategyBase(ABC):
    """
    Abstract base class for all trading strategies

    All strategies must inherit from this class and implement:
    - on_bar(): Called on each new bar
    - get_name(): Return strategy name

    Optional overrides:
    - on_start(): Called at backtest start
    - on_end(): Called at backtest end
    - get_parameters(): Return strategy parameters
    """

    def __init__(self, symbol: str, params: Optional[Dict[str, Any]] = None):
        """
        Initialize strategy

        Args:
            symbol: Trading pair symbol
            params: Strategy parameters
        """
        self.symbol = symbol
        self.params = params or {}

        # Price history storage
        self._prices: List[float] = []
        self._highs: List[float] = []
        self._lows: List[float] = []
        self._volumes: List[float] = []
        self._timestamps: List[datetime] = []

        # Current position state
        self._position_side: Optional[str] = None  # "long" or "short"
        self._position_entry_price: Optional[float] = None

        # Indicators cache
        self._indicators: Dict[str, List[float]] = {}

        logger.info(f"Strategy {self.get_name()} initialized for {symbol}")

    @abstractmethod
    def get_name(self) -> str:
        """Return strategy name"""
        pass

    @abstractmethod
    def on_bar(self, bar: OHLCV, equity: float) -> Optional[Signal]:
        """
        Called on each new bar - generate trading signal

        Args:
            bar: Current OHLCV bar
            equity: Current account equity

        Returns:
            Signal if action should be taken, None otherwise
        """
        pass

    def on_start(self, initial_equity: float) -> None:
        """Called at backtest start"""
        logger.info(f"Strategy {self.get_name()} starting with equity: {initial_equity}")

    def on_end(self, final_equity: float) -> None:
        """Called at backtest end"""
        logger.info(f"Strategy {self.get_name()} ended with equity: {final_equity}")

    def get_parameters(self) -> Dict[str, Any]:
        """Return strategy parameters"""
        return self.params.copy()

    def update_position(self, side: Optional[str], entry_price: Optional[float]) -> None:
        """Update internal position tracking"""
        self._position_side = side
        self._position_entry_price = entry_price

    def has_position(self) -> bool:
        """Check if strategy has open position"""
        return self._position_side is not None

    def is_long(self) -> bool:
        """Check if in long position"""
        return self._position_side == "long"

    def is_short(self) -> bool:
        """Check if in short position"""
        return self._position_side == "short"

    def add_bar(self, bar: OHLCV) -> None:
        """Add bar to history (called by engine before on_bar)"""
        self._prices.append(bar.close)
        self._highs.append(bar.high)
        self._lows.append(bar.low)
        self._volumes.append(bar.volume)
        self._timestamps.append(bar.timestamp)

    def get_prices(self, count: Optional[int] = None) -> List[float]:
        """Get recent close prices"""
        if count is None:
            return self._prices.copy()
        return self._prices[-count:] if len(self._prices) >= count else self._prices.copy()

    def get_highs(self, count: Optional[int] = None) -> List[float]:
        """Get recent high prices"""
        if count is None:
            return self._highs.copy()
        return self._highs[-count:] if len(self._highs) >= count else self._highs.copy()

    def get_lows(self, count: Optional[int] = None) -> List[float]:
        """Get recent low prices"""
        if count is None:
            return self._lows.copy()
        return self._lows[-count:] if len(self._lows) >= count else self._lows.copy()

    # Common indicator calculations
    def sma(self, period: int) -> Optional[float]:
        """Calculate Simple Moving Average"""
        if len(self._prices) < period:
            return None
        return sum(self._prices[-period:]) / period

    def ema(self, period: int) -> Optional[float]:
        """Calculate Exponential Moving Average"""
        if len(self._prices) < period:
            return None

        multiplier = 2 / (period + 1)
        ema_value = sum(self._prices[:period]) / period  # SMA for first value

        for price in self._prices[period:]:
            ema_value = (price * multiplier) + (ema_value * (1 - multiplier))

        return ema_value

    def rsi(self, period: int = 14) -> Optional[float]:
        """Calculate RSI"""
        if len(self._prices) < period + 1:
            return None

        deltas = [self._prices[i] - self._prices[i-1] for i in range(1, len(self._prices))]
        gains = [d if d > 0 else 0 for d in deltas[-period:]]
        losses = [-d if d < 0 else 0 for d in deltas[-period:]]

        avg_gain = sum(gains) / period
        avg_loss = sum(losses) / period

        if avg_loss == 0:
            return 100.0

        rs = avg_gain / avg_loss
        return 100 - (100 / (1 + rs))

    def atr(self, period: int = 14) -> Optional[float]:
        """Calculate Average True Range"""
        if len(self._prices) < period + 1:
            return None

        true_ranges = []
        for i in range(-period, 0):
            high = self._highs[i]
            low = self._lows[i]
            prev_close = self._prices[i - 1]

            tr = max(
                high - low,
                abs(high - prev_close),
                abs(low - prev_close)
            )
            true_ranges.append(tr)

        return sum(true_ranges) / period


class RSIMomentumStrategy(StrategyBase):
    """
    Example RSI Momentum Strategy

    - Buy when RSI crosses above oversold level
    - Sell when RSI crosses below overbought level
    - Uses ATR for stop loss placement
    """

    def __init__(
        self,
        symbol: str,
        rsi_period: int = 14,
        rsi_oversold: float = 30.0,
        rsi_overbought: float = 70.0,
        atr_multiplier: float = 2.0
    ):
        # Set attributes BEFORE calling super().__init__ (which calls get_name)
        self.rsi_period = rsi_period
        self.rsi_oversold = rsi_oversold
        self.rsi_overbought = rsi_overbought
        self.atr_multiplier = atr_multiplier
        self._prev_rsi: Optional[float] = None

        super().__init__(symbol, {
            "rsi_period": rsi_period,
            "rsi_oversold": rsi_oversold,
            "rsi_overbought": rsi_overbought,
            "atr_multiplier": atr_multiplier
        })

    def get_name(self) -> str:
        return f"RSI_Momentum_{self.rsi_period}"

    def on_bar(self, bar: OHLCV, equity: float) -> Optional[Signal]:
        # Calculate indicators
        current_rsi = self.rsi(self.rsi_period)
        current_atr = self.atr(14)

        if current_rsi is None or current_atr is None:
            self._prev_rsi = current_rsi
            return None

        signal = None

        # Check for buy signal (RSI crosses above oversold)
        if not self.has_position():
            if self._prev_rsi is not None:
                if self._prev_rsi <= self.rsi_oversold < current_rsi:
                    # RSI crossed above oversold - BUY
                    stop_loss = bar.close - (current_atr * self.atr_multiplier)
                    take_profit = bar.close + (current_atr * self.atr_multiplier * 2)

                    signal = Signal(
                        signal_type=SignalType.BUY,
                        symbol=self.symbol,
                        price=bar.close,
                        timestamp=bar.timestamp,
                        confidence=min(1.0, (self.rsi_oversold - self._prev_rsi) / 10),
                        stop_loss=stop_loss,
                        take_profit=take_profit,
                        metadata={"rsi": current_rsi, "atr": current_atr}
                    )

        # Check for exit signal (RSI crosses below overbought)
        elif self.is_long():
            if self._prev_rsi is not None:
                if self._prev_rsi >= self.rsi_overbought > current_rsi:
                    # RSI crossed below overbought - CLOSE
                    signal = Signal(
                        signal_type=SignalType.CLOSE_LONG,
                        symbol=self.symbol,
                        price=bar.close,
                        timestamp=bar.timestamp,
                        confidence=0.8,
                        metadata={"rsi": current_rsi, "exit_reason": "rsi_overbought"}
                    )

        self._prev_rsi = current_rsi
        return signal


class RegimeAdaptiveStrategy(StrategyBase):
    """
    Strategy using Regime-Adaptive RSI with Hurst-based thresholds

    Uses HurstExponentCalculator to detect market regime and
    adjusts RSI thresholds accordingly.
    """

    def __init__(
        self,
        symbol: str,
        rsi_period: int = 6,
        hurst_lookback: int = 100,
        atr_multiplier: float = 2.5
    ):
        # Set attributes BEFORE calling super().__init__ (which calls get_name)
        self.rsi_period = rsi_period
        self.hurst_lookback = hurst_lookback
        self.atr_multiplier = atr_multiplier
        self._prev_rsi: Optional[float] = None

        super().__init__(symbol, {
            "rsi_period": rsi_period,
            "hurst_lookback": hurst_lookback,
            "atr_multiplier": atr_multiplier
        })

        # Import regime-adaptive RSI
        from app.trading_enhancements.regime_adaptive_rsi import get_regime_adaptive_rsi
        self._regime_rsi = get_regime_adaptive_rsi()

    def get_name(self) -> str:
        return f"RegimeAdaptive_RSI_{self.rsi_period}"

    def on_bar(self, bar: OHLCV, equity: float) -> Optional[Signal]:
        # Need enough data for Hurst calculation
        if len(self._prices) < self.hurst_lookback:
            return None

        # Calculate ATR for stops
        current_atr = self.atr(14)
        if current_atr is None:
            return None

        # Get regime-adaptive RSI signal
        try:
            result = self._regime_rsi.calculate(
                prices=self._prices,
                atr_value=current_atr,
                use_cache=True
            )
        except Exception as e:
            logger.debug(f"Regime RSI calculation failed: {e}")
            return None

        signal = None

        # Use regime-adaptive signal for entries
        if not self.has_position():
            if result.signal.value == "buy" and result.signal_strength > 0.3:
                stop_loss = bar.close - (current_atr * self.atr_multiplier)
                take_profit = bar.close + (current_atr * self.atr_multiplier * 2)

                signal = Signal(
                    signal_type=SignalType.BUY,
                    symbol=self.symbol,
                    price=bar.close,
                    timestamp=bar.timestamp,
                    confidence=result.signal_strength,
                    stop_loss=stop_loss,
                    take_profit=take_profit,
                    metadata={
                        "rsi": result.rsi_value,
                        "regime": result.market_regime.value,
                        "hurst": result.hurst_value,
                        "thresholds": f"{result.thresholds.oversold}/{result.thresholds.overbought}"
                    }
                )

        # Check for exit
        elif self.is_long():
            if result.signal.value == "sell" or result.rsi_value >= result.thresholds.overbought:
                signal = Signal(
                    signal_type=SignalType.CLOSE_LONG,
                    symbol=self.symbol,
                    price=bar.close,
                    timestamp=bar.timestamp,
                    confidence=0.8,
                    metadata={
                        "rsi": result.rsi_value,
                        "regime": result.market_regime.value,
                        "exit_reason": "regime_rsi_overbought"
                    }
                )

        return signal
