apiVersion: v1
kind: Service
metadata:
  name: timescale-service
  namespace: crypto-bot
  labels:
    app: crypto-trading-bot
    component: database
    database: timescaledb
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    app: crypto-trading-bot
    component: database
    database: timescaledb
