apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
    app: api-gateway
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.global.metrics.enabled }}
    - port: {{ .Values.global.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "api-gateway.selectorLabels" . | nindent 4 }}
    app: api-gateway
