"""Battery #3 maker-mode re-gate of killed candidates (manifest 2026-08-19).

For each of the 6 manifest re-gate items — xs_momentum, lf_trend,
funding_carry, pairs_statarb, vol_breakout, baseline_rsi_ema — trades are
regenerated by the UNCHANGED candidate module (the module code that
already produced a REJECT is never touched), passed through
`edge_lab.maker_fill.apply_maker_fill` to drop entries that would not
actually have filled as a resting limit order, then screened through the
existing `gate1.run_gate1` -> `screen.screen_trades` pipeline. Gate 1 here
reads the MAKER verdict (`ratio_maker >= HURDLE_MULTIPLE`), not the taker
verdict `screen_trades` itself returns — `screen.py` is never modified;
this runner computes the maker verdict from the maker columns
`screen_trades` already exposes (`cost_bps_maker`, `net_maker`,
`ratio_maker`) using the identical hurdle rule, and every verdict says so
explicitly. A maker-mode PASS at Gate 1 still has to clear the SAME Gate 2
DSR/CPCV bar as every other trial — costs going down is not itself a
pass.

Representative-variant rule (decided BEFORE any maker-mode result was
observed, so it cannot be data-mined post-hoc): for the 4 candidates with
more than one pre-registered variant, this runner re-gates the ONE variant
with the highest recorded `ratio_taker` in that candidate's most recent
verdict (`.planning/evidence/killtests/<candidate>-verdict-20260818.json`)
— the variant closest to clearing Gate 1 under taker costs is the one
where a pure cost-model artifact would show up, which is exactly the
question B3 asks. vol_breakout has only one variant, so there is no
choice to make. See `_MAKER_REGATE_VARIANT` for the recorded picks and
their source ratios.

baseline_rsi_ema (manifest item #8) has no prior edge_lab variant to draw
from — the module the RSI9/EMA20 baseline was never a candidate. Its
trades are regenerated fresh via `audit._harness` (`baseline_strategy` +
`make_engine`) over the full clean-epoch h1 history of the 5 majors
(BTC/ETH/SOL/BNB/ADA), then filtered to entries at or after the manifest's
clean-data epoch (2026-04-25) — the pre-epoch bars are still fed to the
engine for indicator warm-up, per the manifest's Amendment 1(c). This is a
DIFFERENT run from the already-executed 2026-08-19 3-fold walk-forward
baseline (commit `2afbbd3`, `backtesting/results/
wf_baseline_fixed_engine_2026-08-19.txt`): that run is recorded in the
ledger separately as `baseline_rsi_ema_walkforward_taker` by
`record_walkforward_baseline_trial`, is NOT re-executed by this module,
and must never be confused with this module's own `baseline_rsi_ema`
maker-regate trial.

Crash isolation matches `run_battery`: one candidate's exception becomes
its ERROR verdict (doc + ledger row still written) and the loop continues.
Every run appends exactly one trial-ledger row per candidate, whatever the
outcome — NO_TRADES-after-fill and Gate-1 KILL included, not just PASS.
"""

from __future__ import annotations

import sys
from pathlib import Path

_BACKTESTING = str(Path(__file__).resolve().parents[1])
_REPO_ROOT = str(Path(__file__).resolve().parents[2])
for _p in (_BACKTESTING, _REPO_ROOT):
    if _p not in sys.path:
        sys.path.insert(0, _p)

import argparse  # noqa: E402
import logging  # noqa: E402
import time  # noqa: E402
import traceback  # noqa: E402
from datetime import datetime, timezone  # noqa: E402
from pathlib import Path as _Path  # noqa: E402
from typing import Any  # noqa: E402

import pandas as pd  # noqa: E402

from edge_lab import trial_ledger  # noqa: E402
from edge_lab.config import HURDLE_MULTIPLE  # noqa: E402
from edge_lab.fetch import interval_ms  # noqa: E402
from edge_lab.gate1 import run_gate1  # noqa: E402
from edge_lab.maker_fill import MAKER_NOTE, apply_maker_fill  # noqa: E402
from edge_lab.run_battery import (  # noqa: E402
    LABEL_HORIZONS,
    date_str_from_ms,
    default_registry,
    load_bundle,
    score_gate2,
    _generate,
)
from edge_lab.trades import Trade, write_trades_csv  # noqa: E402
from edge_lab.universe import load_pin  # noqa: E402
from edge_lab.verdicts import (  # noqa: E402
    render_verdict,
    write_verdict,
    write_verdict_json,
)

logger = logging.getLogger(__name__)

# The 2026-08-19 3-fold walk-forward baseline (commit 2afbbd3). Recorded,
# never re-executed by this module.
WALKFORWARD_BASELINE_RESULT = (
    Path(_BACKTESTING) / "results" / "wf_baseline_fixed_engine_2026-08-19.txt"
)

# name -> (representative variant name, source ratio_taker, source date)
# picked from .planning/evidence/killtests/<name>-verdict-20260818.json —
# highest ratio_taker among that candidate's pre-registered variants.
_MAKER_REGATE_VARIANT: dict[str, tuple[str, str]] = {
    "xs_momentum": ("lookback_7d", "ratio_taker=1.246 (best of 3)"),
    "lf_trend": ("dc_55_20", "ratio_taker=15.511 (best of 5)"),
    "funding_carry": ("thresh_2x", "ratio_taker=2.603 (best of 5)"),
    "pairs_statarb": ("pairs_volume_top10_60d", "ratio_taker=0.088 (best of 3)"),
    "vol_breakout": ("sqz_default", "only variant"),
}

# candidate -> bundle key, mirrors run_battery._CANDIDATE_SPECS. Needed here
# to pick both the right bars for maker_fill and the right bar interval.
_CANDIDATE_BUNDLE_KEY = {
    "xs_momentum": "daily",
    "lf_trend": "daily",
    "funding_carry": "daily",
    "pairs_statarb": "daily",
    "vol_breakout": "h4",
    "baseline_rsi_ema": "h1",
}
_BUNDLE_KEY_INTERVAL = {"daily": "D", "h4": "240", "h1": "60"}

BASELINE_SYMBOLS = ["BTCUSDT", "ETHUSDT", "SOLUSDT", "BNBUSDT", "ADAUSDT"]
BASELINE_CLEAN_EPOCH_MS = int(pd.Timestamp("2026-04-25", tz="UTC").timestamp() * 1000)


def _iso(ts_ms: int) -> str:
    return datetime.fromtimestamp(ts_ms // 1000, tz=timezone.utc).strftime(
        "%Y-%m-%d %H:%M UTC"
    )


def record_walkforward_baseline_trial(date_str: str) -> dict:
    """Ledger the ALREADY-EXECUTED 2026-08-19 walk-forward baseline
    (commit 2afbbd3) as its own trial, per manifest Amendment 1(a): it is
    a genuinely new executed trial, counted before this battery's 8
    additions, and must never share a ledger row with variant #8's maker
    re-gate of the same underlying strategy. This function only records
    that the trial happened — it does not call the engine.
    """
    entry = {
        "candidate": "baseline_rsi_ema",
        "variant": "baseline_rsi_ema_walkforward_taker",
        "params": {
            "engine": "make_engine() defaults (bybit_perp fees, atr_aware slippage, funding on)",
            "folds": "3",
            "epoch": "clean epoch 2026-04-25..2026-08-06",
        },
        "date": date_str,
        "gate1_verdict": "N/A - walk-forward IS/OOS/DSR gate, not edge_lab screen_trades",
        "gate2_passed": False,  # 5/5 symbols GATE REJECT, DSR 0.000 every symbol
        "source": str(WALKFORWARD_BASELINE_RESULT),
    }
    trial_ledger.append_entries([entry])
    return entry


def _bundle_bars_for(candidate: str, bundle: dict) -> tuple[dict, int]:
    key = _CANDIDATE_BUNDLE_KEY[candidate]
    return bundle[key], interval_ms(_BUNDLE_KEY_INTERVAL[key])


def _regenerate_candidate_trades(
    candidate: str, bundle: dict
) -> tuple[list[Trade], dict]:
    """Re-run the UNCHANGED candidate module for its pre-picked variant.

    Returns (trades, variant_params). Reuses run_battery's own registry and
    `_generate` adapter so the variant's inputs are resolved exactly as the
    original battery resolved them.
    """
    registry = default_registry()
    entry = registry[candidate]
    if entry.get("import_error"):
        raise ImportError(entry["import_error"])
    variant_name, _source_note = _MAKER_REGATE_VARIANT[candidate]
    variant = next(v for v in entry["variants"] if v.name == variant_name)
    trades = _generate(entry, bundle, variant)
    return trades, {str(k): str(v) for k, v in variant.params}


def _regenerate_baseline_trades(bundle: dict) -> tuple[list[Trade], dict]:
    """RSI9/EMA20 baseline (audit._harness), regenerated fresh over the 5
    majors' full clean-epoch h1 history. Pre-epoch bars still feed the
    engine for indicator warm-up (manifest Amendment 1(c)); only trades
    whose ENTRY lands at or after the clean epoch are kept.
    """
    from audit._harness import baseline_strategy, load_candles, make_engine  # noqa: E402
    from backtesting.backtest_engine import OrderType  # noqa: E402

    engine_kwargs = {}
    trades: list[Trade] = []
    for symbol in BASELINE_SYMBOLS:
        csv_path = _Path(_BACKTESTING) / "data" / f"{symbol}_60m_365d_bybit.csv"
        if not csv_path.is_file():
            logger.warning(
                "baseline_rsi_ema: no h1 CSV for %s at %s — skipped", symbol, csv_path
            )
            continue
        data = load_candles(csv_path)
        engine = make_engine(**engine_kwargs)
        result = engine.run_backtest(
            data, baseline_strategy, f"{symbol}_baseline_maker_regate"
        )
        for t in result.trades:
            entry_ts_ms = int(pd.Timestamp(t.entry_time).value // 1_000_000)
            if entry_ts_ms < BASELINE_CLEAN_EPOCH_MS:
                continue
            exit_ts_ms = int(pd.Timestamp(t.exit_time).value // 1_000_000)
            side = "LONG" if t.order_type == OrderType.BUY else "SHORT"
            trades.append(
                Trade(
                    symbol=symbol,
                    side=side,
                    entry_ts_ms=entry_ts_ms,
                    exit_ts_ms=exit_ts_ms,
                    entry_px=float(t.entry_price),
                    exit_px=float(t.exit_price),
                )
            )
    return trades, {
        "strategy": "RSI9_EMA20_baseline",
        "symbols": ",".join(BASELINE_SYMBOLS),
    }


def _score_maker_regate(
    candidate: str,
    bundle: dict,
    funding_dir: Path,
    out_dir: Path,
    date_str: str,
    num_trials_floor: int,
) -> dict[str, Any]:
    if candidate == "baseline_rsi_ema":
        raw_trades, params = _regenerate_baseline_trades(bundle)
        variant_name = "baseline_rsi_ema"
    else:
        raw_trades, params = _regenerate_candidate_trades(candidate, bundle)
        variant_name = _MAKER_REGATE_VARIANT[candidate][0] + "_maker"

    bars, bar_interval_ms = _bundle_bars_for(candidate, bundle)
    fill = apply_maker_fill(raw_trades, bars, bar_interval_ms)

    record: dict[str, Any] = {
        "variant": variant_name,
        "params": params,
        "n_trades": len(fill.filled),
        "n_trades_before_fill": len(raw_trades),
        "missed": fill.missed,
        "fill_rate": fill.fill_rate,
        "maker_note": MAKER_NOTE,
        "gate2_passed": None,
    }

    if not fill.filled:
        record["gate1_verdict"] = "NO_TRADES"
        record["gate2_passed"] = False
        return record

    csv_path = Path(out_dir) / "trades" / date_str / f"{candidate}_maker_regate.csv"
    write_trades_csv(fill.filled, csv_path)
    record["trades_csv"] = str(csv_path)

    screened = run_gate1(csv_path, funding_dir)
    maker_gate1_verdict = "PASS" if screened.ratio_maker >= HURDLE_MULTIPLE else "KILL"
    record.update(
        gate1_verdict=maker_gate1_verdict,
        gate1_verdict_basis=(
            "MAKER (ratio_maker >= hurdle_multiple), computed in this runner from "
            "screen_trades' returned maker columns (cost_bps_maker/net_maker/"
            "ratio_maker) — screen.py's own `verdict` field is TAKER-only and is "
            "not read here; screen.py was not modified."
        ),
        gross_edge_bps=screened.gross_edge_bps,
        cost_bps_taker=screened.cost_bps_taker,
        cost_bps_maker=screened.cost_bps_maker,
        ratio_taker=screened.ratio_taker,
        ratio_maker=screened.ratio_maker,
        net_taker=screened.net_taker,
        net_maker=screened.net_maker,
        funding_total=screened.funding_total,
        funding_missing=list(screened.funding_symbols_missing),
        notional_provenance=screened.notional_provenance,
    )
    if maker_gate1_verdict != "PASS":
        record["gate2_passed"] = False
        return record

    gate2, start_ms, end_ms, horizon, dropped = score_gate2(
        fill.filled, bundle["daily"], candidate, funding_dir, num_trials_floor
    )
    record.update(
        gate2_trades_dropped_no_daily=dict(sorted(dropped.items())),
        gate2_n_trades_scored=len(fill.filled) - sum(dropped.values()),
        dsr=gate2.dsr,
        pooled_pf=gate2.pooled_pf,
        positive_path_frac=gate2.positive_path_frac,
        n_paths_valid=gate2.n_paths_valid,
        n_samples=gate2.n_samples,
        sharpe_mean=gate2.sharpe_mean,
        sharpe_std=gate2.sharpe_std,
        gate2_passed=gate2.passed,
        gate2_reasons=list(gate2.reasons),
        num_trials_used=gate2.num_trials_used,
        label_horizon_days=horizon,
        window_start_ms=start_ms,
        window_end_ms=end_ms,
        window_start_iso=_iso(start_ms),
        window_end_iso=_iso(end_ms),
    )
    if candidate not in LABEL_HORIZONS:
        logger.warning(
            "baseline_rsi_ema is not in run_battery.LABEL_HORIZONS — used the "
            "%d-day default purge/embargo horizon",
            horizon,
        )
    return record


def _maker_appendix(candidate: str, record: dict) -> str:
    if candidate in _MAKER_REGATE_VARIANT:
        variant_name, source_note = _MAKER_REGATE_VARIANT[candidate]
        variant_line = f"{variant_name} (selected pre-hoc: {source_note})"
    else:
        variant_line = "baseline_rsi_ema (regenerated fresh via audit._harness, no prior taker variant)"
    lines = [
        "## Maker fill detail",
        "",
        f"- {MAKER_NOTE}",
        f"- representative variant: {variant_line}",
        f"- trades before fill: {record.get('n_trades_before_fill', 'n/a')}",
        f"- missed (unfilled): {record.get('missed', 'n/a')}",
        f"- fill_rate: {record.get('fill_rate', 'n/a')}",
        f"- trades scored (post-fill): {record.get('n_trades', 'n/a')}",
    ]
    basis = record.get("gate1_verdict_basis")
    if basis:
        lines.append(f"- Gate 1 basis: {basis}")
    if candidate not in LABEL_HORIZONS:
        lines.append(
            "- label_horizon_days: no LABEL_HORIZONS entry for baseline_rsi_ema — "
            "the run_battery default (7 days) was used; see run_battery.py's "
            "DEFAULT_LABEL_HORIZON_DAYS."
        )
    return "\n".join(lines) + "\n"


def run_maker_regate(
    data_dir: Path,
    pin_path: Path,
    out_dir: Path,
    funding_dir: Path,
    now_ms: int,
    candidates: list[str] | None = None,
) -> dict:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    date_str = date_str_from_ms(now_ms)

    pin = load_pin(pin_path)
    bundle, sanity_summary = load_bundle(data_dir, pin, now_ms)

    names = candidates or list(_CANDIDATE_BUNDLE_KEY)  # 5 killed + baseline
    known = {(e["candidate"], e["variant"]) for e in trial_ledger.load_entries()}
    planned_variants = set()
    for name in names:
        if name == "baseline_rsi_ema":
            planned_variants.add((name, "baseline_rsi_ema"))
        else:
            planned_variants.add((name, _MAKER_REGATE_VARIANT[name][0] + "_maker"))
    total_new_variants = len(planned_variants - known)
    effective_floor = trial_ledger.effective_trials_floor(total_new_variants)

    results: dict[str, dict] = {}
    for candidate in names:
        try:
            record = _score_maker_regate(
                candidate, bundle, funding_dir, out_dir, date_str, effective_floor
            )
            verdict_candidate = f"{candidate}_maker_regate"
            body = render_verdict(
                verdict_candidate,
                [record],
                pin,
                sanity_summary,
                date_str,
                num_trials_floor=effective_floor,
            )
            text = body.rstrip() + "\n\n" + _maker_appendix(candidate, record)
        except Exception:
            tb = traceback.format_exc()
            logger.exception("maker re-gate for %s failed", candidate)
            record = {
                "error": tb,
                "variant": None,
                "gate1_verdict": None,
                "gate2_passed": False,
            }
            verdict_candidate = f"{candidate}_maker_regate"
            try:
                text = render_verdict(
                    verdict_candidate,
                    [record],
                    pin,
                    sanity_summary,
                    date_str,
                    num_trials_floor=effective_floor,
                )
            except Exception:
                logger.exception(
                    "failed to render the %s maker-regate verdict doc", candidate
                )
                text = f"# {verdict_candidate} verdict: ERROR\n\n```\n{tb}\n```\n"

        results[candidate] = record

        try:
            write_verdict(text, verdict_candidate, date_str, out_dir)
            write_verdict_json(
                verdict_candidate,
                [record],
                pin,
                date_str,
                out_dir,
                num_trials_floor=effective_floor,
            )
        except Exception:
            logger.exception(
                "failed to write the %s maker-regate verdict doc", candidate
            )
            record["doc_error"] = traceback.format_exc()

        # Ledgered per candidate, whatever the outcome — crash isolation
        # must not cost the ledger row for a candidate that already scored.
        try:
            variant_name = record.get("variant") or (
                "baseline_rsi_ema"
                if candidate == "baseline_rsi_ema"
                else _MAKER_REGATE_VARIANT[candidate][0] + "_maker"
            )
            trial_ledger.append_entries(
                [
                    {
                        "candidate": candidate,
                        "variant": variant_name,
                        "params": record.get("params"),
                        "date": date_str,
                        "gate1_verdict": record.get("gate1_verdict"),
                        "gate2_passed": record.get("gate2_passed"),
                    }
                ]
            )
        except Exception:
            logger.exception("failed to append %s to the trial ledger", candidate)
            record["ledger_error"] = traceback.format_exc()

    return results


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Maker-mode re-gate of the 6 battery-#3 killed candidates"
    )
    parser.add_argument("--data-dir", default="backtesting/data")
    parser.add_argument(
        "--pin",
        default="backtesting/edge_lab/universe_2026-08-17.json",
        help="universe_<date>.json",
    )
    parser.add_argument("--out", default=".planning/evidence/killtests")
    parser.add_argument(
        "--date", default=None, help="YYYY-MM-DD; see run_battery --date"
    )
    parser.add_argument(
        "--skip-walkforward-record",
        action="store_true",
        help="skip appending the baseline_rsi_ema_walkforward_taker ledger row",
    )
    parser.add_argument(
        "--candidates",
        default=None,
        help=(
            "comma-separated candidate names to re-gate instead of all 6 "
            "(xs_momentum,lf_trend,funding_carry,pairs_statarb,vol_breakout,"
            "baseline_rsi_ema). Defaults to all 6."
        ),
    )
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.INFO, format="%(levelname)s %(name)s: %(message)s"
    )

    if args.date:
        day = datetime.strptime(args.date, "%Y-%m-%d").replace(tzinfo=timezone.utc)
        now_ms = int(day.timestamp() * 1000)
    else:
        now_ms = int(time.time() * 1000)

    date_str = date_str_from_ms(now_ms)
    data_dir = (
        Path(_REPO_ROOT) / args.data_dir
        if not Path(args.data_dir).is_absolute()
        else Path(args.data_dir)
    )
    funding_dir = data_dir / "funding"
    out_dir = (
        Path(_REPO_ROOT) / args.out
        if not Path(args.out).is_absolute()
        else Path(args.out)
    )
    pin_path = (
        Path(_REPO_ROOT) / args.pin
        if not Path(args.pin).is_absolute()
        else Path(args.pin)
    )

    if not args.skip_walkforward_record:
        record_walkforward_baseline_trial(date_str)

    candidates = None
    if args.candidates:
        names = [n.strip() for n in args.candidates.split(",") if n.strip()]
        unknown = [n for n in names if n not in _CANDIDATE_BUNDLE_KEY]
        if unknown:
            raise SystemExit(
                f"--candidates: unknown name(s) {unknown}; known: "
                f"{sorted(_CANDIDATE_BUNDLE_KEY)}"
            )
        candidates = names

    results = run_maker_regate(
        data_dir, pin_path, out_dir, funding_dir, now_ms, candidates
    )
    for candidate, record in results.items():
        logger.info(
            "%s: gate1=%s gate2_passed=%s missed=%s fill_rate=%s",
            candidate,
            record.get("gate1_verdict"),
            record.get("gate2_passed"),
            record.get("missed"),
            record.get("fill_rate"),
        )

    errored = [name for name, rec in results.items() if rec.get("error")]
    if errored:
        logger.error("ERROR verdicts: %s — see the verdict docs", ", ".join(errored))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
