"""Battery #3 maker-mode re-gate of killed candidates (manifest 2026-08-19).

v2 (final-review fix wave, 2026-08-19): the v1 run tested the wrong bar for
5 of 6 candidates (C1) and charged Gate 2 at taker cost inside a maker
re-gate (H2). Both are fixed here; see `_CANDIDATE_ENTRY_BASIS` and
`_maker_regate_round_trip_bps`. v1 artifacts (verdict docs, trades CSVs,
ledger rows) are RETAINED, never deleted or overwritten — every v2 artifact
carries a `_v2` suffix distinct from v1's names, per manifest Amendment 3.

For each of the 6 manifest re-gate items — xs_momentum, lf_trend,
funding_carry, pairs_statarb, vol_breakout, baseline_rsi_ema — trades are
regenerated by the UNCHANGED candidate module (the module code that
already produced a REJECT is never touched), passed through
`edge_lab.maker_fill.apply_maker_fill` to drop entries that would not
actually have filled as a resting limit order, then screened at Gate 1
under the M1 cost model (maker fee, no slippage, on the entry leg; taker
fee + slippage on the exit leg — the conservative, costs-only-go-up
approximation of the manifest's mixed taker-stop/maker-TP exit rule). A
Gate 1 PASS proceeds to Gate 2, scored under the SAME cost model (H2) —
the two gates must not disagree about what a trade costs. `screen.py` and
`run_battery.py`'s own taker-cost Gate 2 path are never modified; this
runner computes its own Gate 1 ratio and its own Gate 2 cost map,
substituting into `gate2.daily_returns_from_trades`/`gate2.run_gate2` (the
actual statistical machinery), which are reused unchanged.

Representative-variant rule (decided BEFORE any maker-mode result was
observed, so it cannot be data-mined post-hoc): for the 4 candidates with
more than one pre-registered variant, this runner re-gates the ONE variant
with the highest recorded `ratio_taker` in that candidate's most recent
verdict (`.planning/evidence/killtests/<candidate>-verdict-20260818.json`)
— the variant closest to clearing Gate 1 under taker costs is the one
where a pure cost-model artifact would show up, which is exactly the
question B3 asks. vol_breakout has only one variant, so there is no
choice to make. See `_MAKER_REGATE_VARIANT` for the recorded picks and
their source ratios.

baseline_rsi_ema (manifest item #8) has no prior edge_lab variant to draw
from — the module the RSI9/EMA20 baseline was never a candidate. Its
trades are regenerated fresh via `audit._harness` (`baseline_strategy` +
`make_engine`) over the full clean-epoch h1 history of the 5 majors
(BTC/ETH/SOL/BNB/ADA), then filtered to entries at or after the manifest's
clean-data epoch (2026-04-25) — the pre-epoch bars are still fed to the
engine for indicator warm-up, per the manifest's Amendment 1(c). This is a
DIFFERENT run from the already-executed 2026-08-19 3-fold walk-forward
baseline (commit `2afbbd3`, `backtesting/results/
wf_baseline_fixed_engine_2026-08-19.txt`): that run is recorded in the
ledger separately as `baseline_rsi_ema_walkforward_taker` by
`record_walkforward_baseline_trial` (idempotent — m1 fix), is NOT
re-executed by this module, and must never be confused with this module's
own `baseline_rsi_ema` maker-regate trial.

baseline_rsi_ema's trades come from `audit._harness.load_candles` (the
FULL raw CSV), while the `bars` frame passed to `apply_maker_fill` is
`bundle["h1"]` (cut at `now_ms` by `run_battery.load_bundle`'s closed-bar
rule). A trade whose entry bar falls outside that cut is scored as a
missed fill rather than silently matched against a bar that would not
actually have been "closed" data at battery time — the conservative
direction, not a defect.

Crash isolation matches `run_battery`: one candidate's exception becomes
its ERROR verdict (doc + ledger row still written) and the loop continues.
Every run appends exactly one trial-ledger row per candidate, whatever the
outcome — NO_TRADES-after-fill and Gate-1 KILL included, not just PASS.
"""

from __future__ import annotations

import sys
from pathlib import Path

_BACKTESTING = str(Path(__file__).resolve().parents[1])
_REPO_ROOT = str(Path(__file__).resolve().parents[2])
for _p in (_BACKTESTING, _REPO_ROOT):
    if _p not in sys.path:
        sys.path.insert(0, _p)

import argparse  # noqa: E402
import logging  # noqa: E402
import time  # noqa: E402
import traceback  # noqa: E402
from datetime import datetime, timezone  # noqa: E402
from decimal import Decimal  # noqa: E402
from pathlib import Path as _Path  # noqa: E402
from typing import Any, Mapping, Sequence  # noqa: E402

import pandas as pd  # noqa: E402
from costs_loader import load_costs, load_funding  # noqa: E402

from edge_lab import trial_ledger  # noqa: E402
from edge_lab.config import (  # noqa: E402
    HURDLE_MULTIPLE,
    SLIPPAGE_BPS,
    SLIPPAGE_FALLBACK_BPS,
)
from edge_lab.fetch import interval_ms  # noqa: E402
from edge_lab.gate1 import run_gate1  # noqa: E402
from edge_lab.gate2 import Gate2Result, daily_returns_from_trades, run_gate2  # noqa: E402
from edge_lab.maker_fill import MAKER_NOTE, apply_maker_fill  # noqa: E402
from edge_lab.run_battery import (  # noqa: E402
    DEFAULT_LABEL_HORIZON_DAYS,
    LABEL_HORIZONS,
    date_str_from_ms,
    default_registry,
    load_bundle,
    _generate,
)
from edge_lab.trades import Trade, gross_pnl, notionals, write_trades_csv  # noqa: E402
from edge_lab.universe import load_pin  # noqa: E402
from edge_lab.verdicts import (  # noqa: E402
    overall_verdict,
    render_summary,
    render_verdict,
    write_verdict,
    write_verdict_json,
)

logger = logging.getLogger(__name__)

_costs = load_costs()
_BPS = Decimal("10000")

# The 2026-08-19 3-fold walk-forward baseline (commit 2afbbd3). Recorded,
# never re-executed by this module.
WALKFORWARD_BASELINE_RESULT = (
    Path(_BACKTESTING) / "results" / "wf_baseline_fixed_engine_2026-08-19.txt"
)

# name -> (representative variant name, source ratio_taker, source date)
# picked from .planning/evidence/killtests/<name>-verdict-20260818.json —
# highest ratio_taker among that candidate's pre-registered variants.
_MAKER_REGATE_VARIANT: dict[str, tuple[str, str]] = {
    "xs_momentum": ("lookback_7d", "ratio_taker=1.246 (best of 3)"),
    "lf_trend": ("dc_55_20", "ratio_taker=15.511 (best of 5)"),
    "funding_carry": ("thresh_2x", "ratio_taker=2.603 (best of 5)"),
    "pairs_statarb": ("pairs_volume_top10_60d", "ratio_taker=0.088 (best of 3)"),
    "vol_breakout": ("sqz_default", "only variant"),
}

# candidate -> bundle key, mirrors run_battery._CANDIDATE_SPECS. Needed here
# to pick both the right bars for maker_fill and the right bar interval.
_CANDIDATE_BUNDLE_KEY = {
    "xs_momentum": "daily",
    "lf_trend": "daily",
    "funding_carry": "daily",
    "pairs_statarb": "daily",
    "vol_breakout": "h4",
    "baseline_rsi_ema": "h1",
}
_BUNDLE_KEY_INTERVAL = {"daily": "D", "h4": "240", "h1": "60"}

# entry_basis per candidate (final-review C1) — each verified against its
# OWN source, not assumed from the others' shape:
_CANDIDATE_ENTRY_BASIS: dict[str, str] = {
    # xs_momentum.py:112-115 `entry_ts_ms=m, entry_px=opens[sym][m]` — the
    # rebalance bar's own open.
    "xs_momentum": "open",
    # lf_trend.py:154,167-170 `fill_idx=t+1; entry_ts_ms=ts[entry_idx],
    # entry_px=open_[entry_idx]` — same bar, its own open.
    "lf_trend": "open",
    # funding_carry.py:235,256 `position=(side, t, o)` inside
    # `for t, o in zip(ts_list, open_list)` — entry_ts_ms=t, entry_px=o,
    # same bar's own open.
    "funding_carry": "open",
    # vol_breakout.py:140,147,156-157 `entry_idx=t+1; entry_px=open_[entry_idx];
    # pos_entry_idx=entry_idx` then `entry_ts_ms=ts[pos_entry_idx]` — same
    # bar, its own open.
    "vol_breakout": "open",
    # pairs_statarb.py:263-264,277-278 `ts=common[idx]; price_i=closes[sym_i][ts]`
    # then `"entry_ts": ts, "entry_px_i": price_i` — same bar's own CLOSE,
    # not open. The only re-gated candidate matching maker_fill's original
    # ("close") shape.
    "pairs_statarb": "close",
    # backtest_engine.py:310-319 (Invariant A) + :432-462: a pending signal
    # is executed at THIS bar's open (`fill_price = row["open"]`) using
    # THIS bar's own `current_time` — entry_time and entry_price both
    # anchor to the SAME bar, exactly like the four candidates above.
    # Empirically confirmed (task report): for every checked trade,
    # entry_price / matching-bar-open equals 1 +/- 0.0005 (the ATR-floor
    # slippage), not anywhere near that bar's close. The final-review's
    # m2 finding traced only :460 (`entry_price = price * (1 +/- slip)`)
    # in isolation and missed that the pending-signal caller (~:315)
    # supplies `price = row["open"]`, not a close — corrected here.
    "baseline_rsi_ema": "open",
}

BASELINE_SYMBOLS = ["BTCUSDT", "ETHUSDT", "SOLUSDT", "BNBUSDT", "ADAUSDT"]
BASELINE_CLEAN_EPOCH_MS = int(pd.Timestamp("2026-04-25", tz="UTC").timestamp() * 1000)


def _iso(ts_ms: int) -> str:
    return datetime.fromtimestamp(ts_ms // 1000, tz=timezone.utc).strftime(
        "%Y-%m-%d %H:%M UTC"
    )


def _fmt_dec(value: Any, digits: int = 4) -> str:
    if value is None:
        return "n/a"
    return f"{Decimal(value):.{digits}f}"


def _v2_variant_name(candidate: str) -> str:
    if candidate == "baseline_rsi_ema":
        return "baseline_rsi_ema_v2"
    return _MAKER_REGATE_VARIANT[candidate][0] + "_maker_v2"


def record_walkforward_baseline_trial(date_str: str) -> dict | None:
    """Ledger the ALREADY-EXECUTED 2026-08-19 walk-forward baseline
    (commit 2afbbd3) as its own trial, per manifest Amendment 1(a): it is
    a genuinely new executed trial, counted before this battery's 8
    additions, and must never share a ledger row with variant #8's maker
    re-gate of the same underlying strategy. This function only records
    that the trial happened — it does not call the engine.

    Idempotent (final-review m1): every prior call already appended this
    exact (candidate, variant) pair, so a re-invocation (e.g. re-running
    the v2 re-gate) must not silently duplicate it — raw-vs-distinct
    ledger divergence is a live concern per Amendment 2(e).
    """
    key = ("baseline_rsi_ema", "baseline_rsi_ema_walkforward_taker")
    existing = trial_ledger.load_entries()
    if any((e.get("candidate"), e.get("variant")) == key for e in existing):
        logger.info("%s/%s already ledgered — skipping duplicate append", *key)
        return None
    entry = {
        "candidate": key[0],
        "variant": key[1],
        "params": {
            "engine": "make_engine() defaults (bybit_perp fees, atr_aware slippage, funding on)",
            "folds": "3",
            "epoch": "clean epoch 2026-04-25..2026-08-06",
        },
        "date": date_str,
        "gate1_verdict": "N/A - walk-forward IS/OOS/DSR gate, not edge_lab screen_trades",
        "gate2_passed": False,  # 5/5 symbols GATE REJECT, DSR 0.000 every symbol
        "source": str(WALKFORWARD_BASELINE_RESULT),
    }
    trial_ledger.append_entries([entry])
    return entry


def _bundle_bars_for(candidate: str, bundle: dict) -> tuple[dict, int]:
    key = _CANDIDATE_BUNDLE_KEY[candidate]
    return bundle[key], interval_ms(_BUNDLE_KEY_INTERVAL[key])


def _regenerate_candidate_trades(
    candidate: str, bundle: dict
) -> tuple[list[Trade], dict]:
    """Re-run the UNCHANGED candidate module for its pre-picked variant.

    Returns (trades, variant_params). Reuses run_battery's own registry and
    `_generate` adapter so the variant's inputs are resolved exactly as the
    original battery resolved them.
    """
    registry = default_registry()
    entry = registry[candidate]
    if entry.get("import_error"):
        raise ImportError(entry["import_error"])
    variant_name, _source_note = _MAKER_REGATE_VARIANT[candidate]
    variant = next(v for v in entry["variants"] if v.name == variant_name)
    trades = _generate(entry, bundle, variant)
    return trades, {str(k): str(v) for k, v in variant.params}


def _regenerate_baseline_trades(bundle: dict) -> tuple[list[Trade], dict]:
    """RSI9/EMA20 baseline (audit._harness), regenerated fresh over the 5
    majors' full clean-epoch h1 history. Pre-epoch bars still feed the
    engine for indicator warm-up (manifest Amendment 1(c)); only trades
    whose ENTRY lands at or after the clean epoch are kept.
    """
    from audit._harness import baseline_strategy, load_candles, make_engine  # noqa: E402
    from backtesting.backtest_engine import OrderType  # noqa: E402

    trades: list[Trade] = []
    for symbol in BASELINE_SYMBOLS:
        csv_path = _Path(_BACKTESTING) / "data" / f"{symbol}_60m_365d_bybit.csv"
        if not csv_path.is_file():
            logger.warning(
                "baseline_rsi_ema: no h1 CSV for %s at %s — skipped", symbol, csv_path
            )
            continue
        data = load_candles(csv_path)
        engine = make_engine()
        result = engine.run_backtest(
            data, baseline_strategy, f"{symbol}_baseline_maker_regate_v2"
        )
        for t in result.trades:
            entry_ts_ms = int(pd.Timestamp(t.entry_time).value // 1_000_000)
            if entry_ts_ms < BASELINE_CLEAN_EPOCH_MS:
                continue
            exit_ts_ms = int(pd.Timestamp(t.exit_time).value // 1_000_000)
            side = "LONG" if t.order_type == OrderType.BUY else "SHORT"
            trades.append(
                Trade(
                    symbol=symbol,
                    side=side,
                    entry_ts_ms=entry_ts_ms,
                    exit_ts_ms=exit_ts_ms,
                    entry_px=float(t.entry_price),
                    exit_px=float(t.exit_price),
                )
            )
    return trades, {
        "strategy": "RSI9_EMA20_baseline",
        "symbols": ",".join(BASELINE_SYMBOLS),
    }


def _maker_regate_round_trip_bps(symbol: str) -> Decimal:
    """M1 conservative compliant cost model: maker fee (NO slippage — a
    resting order fills at the price it posted) on the entry leg; taker
    fee PLUS the same per-symbol slippage table on the exit leg. This is
    the upper bound of the manifest's frozen mixed exit rule (stop=taker,
    TP/time=maker-with-its-own-trade-through-test, fallback to taker) —
    costs only go up relative to the frozen model, never down, per plan
    §5.2. `round_trip_cost_bps` (services/trading-engine/app/costs.py)
    already supports mixed entry/exit liquidity directly; no new cost
    function is needed.

    Used as BOTH the Gate 1 hurdle cost (`_mixed_gate1`) and the Gate 2
    cost_bps_rt map (`_score_gate2_maker`, H2 fix) — the two gates must
    not run on different cost models.
    """
    return _costs.round_trip_cost_bps(
        symbol,
        entry_liquidity=_costs.Liquidity.MAKER,
        exit_liquidity=_costs.Liquidity.TAKER,
        schedule=_costs.FeeSchedule.bybit_linear_perp(),
        slippage_table=SLIPPAGE_BPS,
        slippage_fallback=SLIPPAGE_FALLBACK_BPS,
    )


def _mixed_gate1(trades: Sequence[Trade]) -> dict[str, Decimal]:
    """Gate 1 hurdle math under the M1 cost model.

    Mirrors `screen.screen_trades`' own notional-weighted-average formula
    exactly (same algorithm: per-symbol bps cached once, weighted by each
    trade's average leg notional, ratio = gross_edge_bps / cost_bps) —
    `screen_trades` has no mixed-liquidity mode and `screen.py` is never
    modified, so the substitution happens here rather than there.
    """
    gross_total = Decimal("0")
    leg_notional_total = Decimal("0")
    cost_total = Decimal("0")
    bps_cache: dict[str, Decimal] = {}
    for t in trades:
        n_in, n_out = notionals(t)
        avg_leg = (n_in + n_out) / 2
        gross_total += gross_pnl(t)
        leg_notional_total += avg_leg
        if t.symbol not in bps_cache:
            bps_cache[t.symbol] = _maker_regate_round_trip_bps(t.symbol)
        cost_total += avg_leg * bps_cache[t.symbol] / _BPS
    gross_edge_bps = (gross_total / leg_notional_total) * _BPS
    cost_bps_mixed = (cost_total / leg_notional_total) * _BPS
    ratio_mixed = (
        gross_edge_bps / cost_bps_mixed if cost_bps_mixed > 0 else Decimal("0")
    )
    return {
        "gross_edge_bps": gross_edge_bps,
        "cost_bps_mixed": cost_bps_mixed,
        "ratio_mixed": ratio_mixed,
        "gross_total": gross_total,
        "cost_total": cost_total,
    }


def _score_gate2_maker(
    trades: Sequence[Trade],
    daily: Mapping[str, pd.DataFrame],
    candidate: str,
    funding_dir: Path,
    num_trials_floor: int,
) -> tuple[Gate2Result, int, int, int, dict[str, int]]:
    """Mirrors `run_battery.score_gate2` exactly (window computation,
    dropped-trade handling, LABEL_HORIZONS lookup) except the per-symbol
    cost map is the M1 maker-entry/taker-exit model, not run_battery's
    taker/taker `round_trip_bps` (H2). `run_battery.py` itself is
    untouched — this reuses `gate2.daily_returns_from_trades` /
    `gate2.run_gate2` (the actual CPCV/DSR machinery) unchanged; only the
    cost map differs.
    """
    scored: list[Trade] = []
    dropped: dict[str, int] = {}
    for t in trades:
        if t.symbol in daily:
            scored.append(t)
        else:
            dropped[t.symbol] = dropped.get(t.symbol, 0) + 1
    if dropped:
        logger.warning(
            "%s (maker v2): dropping %d of %d trades from Gate 2 — no daily "
            "frame for %s",
            candidate,
            sum(dropped.values()),
            len(trades),
            ", ".join(f"{s} ({n})" for s, n in sorted(dropped.items())),
        )
    if not scored:
        raise RuntimeError(
            f"every one of the {len(trades)} {candidate} maker-v2 trades is "
            "on a symbol with no daily frame — Gate 2 has nothing to score."
        )
    trades = scored

    symbols = {t.symbol for t in trades}
    cost_bps_rt = {symbol: _maker_regate_round_trip_bps(symbol) for symbol in symbols}
    funding = {symbol: load_funding(symbol, str(funding_dir)) for symbol in symbols}

    start_ms = min(t.entry_ts_ms for t in trades)
    data_end = max(
        (int(df["ts_ms"].iloc[-1]) for df in daily.values() if len(df)),
        default=start_ms,
    )
    end_ms = max(data_end, max(t.exit_ts_ms for t in trades))

    returns = daily_returns_from_trades(
        trades, daily, start_ms, end_ms, cost_bps_rt, funding
    )
    horizon = LABEL_HORIZONS.get(candidate, DEFAULT_LABEL_HORIZON_DAYS)
    if candidate not in LABEL_HORIZONS:
        logger.warning(
            "%s not in run_battery.LABEL_HORIZONS — using the %d-day default "
            "purge/embargo horizon",
            candidate,
            horizon,
        )
    return (
        run_gate2(returns, horizon, num_trials_floor=num_trials_floor),
        start_ms,
        end_ms,
        horizon,
        dropped,
    )


def _score_maker_regate(
    candidate: str,
    bundle: dict,
    funding_dir: Path,
    out_dir: Path,
    date_str: str,
    num_trials_floor: int,
) -> dict[str, Any]:
    if candidate == "baseline_rsi_ema":
        raw_trades, params = _regenerate_baseline_trades(bundle)
    else:
        raw_trades, params = _regenerate_candidate_trades(candidate, bundle)
    variant_name = _v2_variant_name(candidate)

    bars, bar_interval_ms = _bundle_bars_for(candidate, bundle)
    entry_basis = _CANDIDATE_ENTRY_BASIS[candidate]
    fill = apply_maker_fill(raw_trades, bars, bar_interval_ms, entry_basis=entry_basis)

    record: dict[str, Any] = {
        "variant": variant_name,
        "params": params,
        "n_trades": len(fill.filled),
        "n_trades_before_fill": len(raw_trades),
        "missed": fill.missed,
        "fill_rate": fill.fill_rate,
        "maker_note": MAKER_NOTE,
        "entry_basis": entry_basis,
        "gate2_passed": None,
    }

    if not fill.filled:
        record["gate1_verdict"] = "NO_TRADES"
        record["gate2_passed"] = False
        return record

    csv_path = Path(out_dir) / "trades" / date_str / f"{candidate}_maker_regate_v2.csv"
    write_trades_csv(fill.filled, csv_path)
    record["trades_csv"] = str(csv_path)

    # Informational reference columns (pure TAKER, pure MAKER-both-legs)
    # via the existing, unmodified gate1/screen_trades pipeline. NOT the
    # verdict basis (see gate1_verdict_basis below).
    screened = run_gate1(csv_path, funding_dir)

    mixed = _mixed_gate1(fill.filled)
    mixed_gate1_verdict = "PASS" if mixed["ratio_mixed"] >= HURDLE_MULTIPLE else "KILL"
    net_mixed = mixed["gross_total"] - mixed["cost_total"] - screened.funding_total

    record.update(
        gate1_verdict=mixed_gate1_verdict,
        gate1_verdict_basis=(
            "M1 conservative mixed cost model (maker fee, no slippage, on "
            "the entry leg; taker fee + slippage on the exit leg), computed "
            "in this runner via _mixed_gate1 — NOT screen_trades' own "
            "pure-TAKER verdict or pure-MAKER-both-legs ratio_maker column, "
            "both still reported below for reference only. screen.py was "
            "not modified."
        ),
        gross_edge_bps=screened.gross_edge_bps,
        cost_bps_taker=screened.cost_bps_taker,
        cost_bps_maker=screened.cost_bps_maker,
        ratio_taker=screened.ratio_taker,
        ratio_maker=screened.ratio_maker,
        net_taker=screened.net_taker,
        net_maker=screened.net_maker,
        cost_bps_mixed=mixed["cost_bps_mixed"],
        ratio_mixed=mixed["ratio_mixed"],
        net_mixed=net_mixed,
        funding_total=screened.funding_total,
        funding_missing=list(screened.funding_symbols_missing),
        notional_provenance=screened.notional_provenance,
    )
    if mixed_gate1_verdict != "PASS":
        record["gate2_passed"] = False
        return record

    gate2, start_ms, end_ms, horizon, dropped = _score_gate2_maker(
        fill.filled, bundle["daily"], candidate, funding_dir, num_trials_floor
    )
    record.update(
        gate2_trades_dropped_no_daily=dict(sorted(dropped.items())),
        gate2_n_trades_scored=len(fill.filled) - sum(dropped.values()),
        dsr=gate2.dsr,
        pooled_pf=gate2.pooled_pf,
        positive_path_frac=gate2.positive_path_frac,
        n_paths_valid=gate2.n_paths_valid,
        n_samples=gate2.n_samples,
        sharpe_mean=gate2.sharpe_mean,
        sharpe_std=gate2.sharpe_std,
        gate2_passed=gate2.passed,
        gate2_reasons=list(gate2.reasons),
        num_trials_used=gate2.num_trials_used,
        label_horizon_days=horizon,
        window_start_ms=start_ms,
        window_end_ms=end_ms,
        window_start_iso=_iso(start_ms),
        window_end_iso=_iso(end_ms),
        gate2_cost_basis=(
            "M1 maker-entry/taker-exit cost map (H2 fix) — the SAME model "
            "as Gate 1 above, NOT run_battery.score_gate2's taker/taker "
            "round_trip_bps."
        ),
    )
    return record


def _maker_appendix(candidate: str, record: dict) -> str:
    if candidate in _MAKER_REGATE_VARIANT:
        variant_name, source_note = _MAKER_REGATE_VARIANT[candidate]
        variant_line = f"{variant_name} (selected pre-hoc: {source_note})"
    else:
        variant_line = (
            "baseline_rsi_ema (regenerated fresh via audit._harness, no "
            "prior taker variant)"
        )
    lines = [
        "## Maker fill detail (v2 — corrected per final-review C1/H2/M1)",
        "",
        f"- {MAKER_NOTE}",
        f"- representative variant: {variant_line}",
        f"- entry basis: {record.get('entry_basis', 'n/a')} "
        "(see run_maker_regate.py's _CANDIDATE_ENTRY_BASIS for the "
        "source-line citation)",
        f"- trades before fill: {record.get('n_trades_before_fill', 'n/a')}",
        f"- missed (unfilled): {record.get('missed', 'n/a')}",
        f"- fill_rate: {record.get('fill_rate', 'n/a')}",
        f"- trades scored (post-fill): {record.get('n_trades', 'n/a')}",
    ]
    basis = record.get("gate1_verdict_basis")
    if basis:
        lines.append(f"- Gate 1 basis: {basis}")
    if record.get("cost_bps_mixed") is not None:
        lines.append(
            "- M1 mixed cost model: cost_bps_mixed="
            f"{_fmt_dec(record.get('cost_bps_mixed'))} ratio_mixed="
            f"{_fmt_dec(record.get('ratio_mixed'), 3)} net_mixed="
            f"{_fmt_dec(record.get('net_mixed'))} — this is the figure "
            "gate1_verdict above is actually computed from. The table's "
            "ratio_taker/cost_bps_taker are the pure-TAKER reference "
            "(informational only); ratio_maker/cost_bps_maker are the "
            "pure-MAKER-both-legs reference (informational only, cheaper "
            "than the frozen model per M1 — not the verdict basis)."
        )
    gate2_basis = record.get("gate2_cost_basis")
    if gate2_basis:
        lines.append(f"- Gate 2 basis: {gate2_basis}")
    if candidate not in LABEL_HORIZONS:
        lines.append(
            "- label_horizon_days: no LABEL_HORIZONS entry for "
            f"{candidate} — the run_battery default "
            f"({DEFAULT_LABEL_HORIZON_DAYS} days) was used."
        )
    if candidate == "baseline_rsi_ema":
        lines.append(
            "- baseline_rsi_ema's trades come from audit._harness.load_candles "
            "(the full raw CSV); the bars frame used for the fill test is "
            "bundle['h1'] (cut at now_ms by load_bundle's closed-bar rule). "
            "A trade whose entry bar falls outside that cut scores as a "
            "missed fill rather than matching a not-yet-closed bar — the "
            "conservative direction, not a defect."
        )
    lines.append(
        "- Supersedes the 2026-08-19 v1 maker re-gate for this candidate "
        f"(`{candidate}_maker_regate-verdict-20260819.md`), which tested "
        "the wrong bar for open-basis candidates (final-review C1) and "
        "charged Gate 2 at taker cost (H2). The v1 artifact is retained, "
        "not deleted, per manifest Amendment 3."
    )
    return "\n".join(lines) + "\n"


def _write_regate_summary(
    results: dict,
    pin: dict,
    sanity_summary: str,
    date_str: str,
    num_trials_floor: int,
    out_dir: Path,
    ledger_count: int | None = None,
) -> Path:
    """Aggregate summary for the 6 maker re-gates (M3) — `render_summary`
    reused verbatim for the table/Gate-0/caveats rendering, written to its
    own path (not `write_summary`'s `battery-summary-<date>.md`, which
    already belongs to the seasonality-only battery run from the same
    date and must not be overwritten)."""
    text = render_summary(
        results,
        pin,
        sanity_summary,
        date_str,
        num_trials_floor=num_trials_floor,
        ledger_count=ledger_count,
    )
    text = text.replace(
        f"# Edge research battery summary — {date_str}",
        f"# Battery #3 maker re-gate (v2) summary — {date_str}",
        1,
    )
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"maker_regate_v2-summary-{date_str}.md"
    path.write_text(text, encoding="utf-8")
    return path


def run_maker_regate(
    data_dir: Path,
    pin_path: Path,
    out_dir: Path,
    funding_dir: Path,
    now_ms: int,
    candidates: list[str] | None = None,
) -> dict:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    date_str = date_str_from_ms(now_ms)

    pin = load_pin(pin_path)
    bundle, sanity_summary = load_bundle(data_dir, pin, now_ms)

    names = candidates or list(_CANDIDATE_BUNDLE_KEY)  # 5 killed + baseline
    known = {(e["candidate"], e["variant"]) for e in trial_ledger.load_entries()}
    planned_variants = {(name, _v2_variant_name(name)) for name in names}
    total_new_variants = len(planned_variants - known)
    effective_floor = trial_ledger.effective_trials_floor(total_new_variants)
    # Reported in every verdict artifact alongside the floor (decision of
    # record 2026-08-20): the raw ledger component before the static-floor
    # max, so a reader can audit which side of max(floor, n_paths) bound.
    ledger_count = trial_ledger.effective_trial_count(total_new_variants)

    results: dict[str, dict] = {}
    for candidate in names:
        verdict_candidate = f"{candidate}_maker_regate_v2"
        try:
            record = _score_maker_regate(
                candidate, bundle, funding_dir, out_dir, date_str, effective_floor
            )
            body = render_verdict(
                verdict_candidate,
                [record],
                pin,
                sanity_summary,
                date_str,
                num_trials_floor=effective_floor,
                ledger_count=ledger_count,
            )
            text = body.rstrip() + "\n\n" + _maker_appendix(candidate, record)
        except Exception:
            tb = traceback.format_exc()
            logger.exception("maker re-gate for %s failed", candidate)
            record = {
                "error": tb,
                "variant": None,
                "gate1_verdict": None,
                "gate2_passed": False,
            }
            try:
                text = render_verdict(
                    verdict_candidate,
                    [record],
                    pin,
                    sanity_summary,
                    date_str,
                    num_trials_floor=effective_floor,
                    ledger_count=ledger_count,
                )
            except Exception:
                logger.exception(
                    "failed to render the %s maker-regate verdict doc", candidate
                )
                text = f"# {verdict_candidate} verdict: ERROR\n\n```\n{tb}\n```\n"

        results[candidate] = record

        try:
            write_verdict(text, verdict_candidate, date_str, out_dir)
            write_verdict_json(
                verdict_candidate,
                [record],
                pin,
                date_str,
                out_dir,
                num_trials_floor=effective_floor,
                ledger_count=ledger_count,
            )
        except Exception:
            logger.exception(
                "failed to write the %s maker-regate verdict doc", candidate
            )
            record["doc_error"] = traceback.format_exc()

        # Ledgered per candidate, whatever the outcome — crash isolation
        # must not cost the ledger row for a candidate that already scored.
        try:
            variant_name = record.get("variant") or _v2_variant_name(candidate)
            trial_ledger.append_entries(
                [
                    {
                        "candidate": candidate,
                        "variant": variant_name,
                        "params": record.get("params"),
                        "date": date_str,
                        "gate1_verdict": record.get("gate1_verdict"),
                        "gate2_passed": record.get("gate2_passed"),
                    }
                ]
            )
        except Exception:
            logger.exception("failed to append %s to the trial ledger", candidate)
            record["ledger_error"] = traceback.format_exc()

    try:
        summary_shaped = {
            name: {"variants": [rec], "verdict": overall_verdict([rec])}
            for name, rec in results.items()
        }
        _write_regate_summary(
            summary_shaped,
            pin,
            sanity_summary,
            date_str,
            effective_floor,
            out_dir,
            ledger_count=ledger_count,
        )
    except Exception:
        logger.exception("failed to write the maker-regate v2 summary")

    return results


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Maker-mode re-gate of the 6 battery-#3 killed candidates"
    )
    parser.add_argument("--data-dir", default="backtesting/data")
    parser.add_argument(
        "--pin",
        default="backtesting/edge_lab/universe_2026-08-17.json",
        help="universe_<date>.json",
    )
    parser.add_argument("--out", default=".planning/evidence/killtests")
    parser.add_argument(
        "--date", default=None, help="YYYY-MM-DD; see run_battery --date"
    )
    parser.add_argument(
        "--skip-walkforward-record",
        action="store_true",
        help="skip appending the baseline_rsi_ema_walkforward_taker ledger row",
    )
    parser.add_argument(
        "--candidates",
        default=None,
        help=(
            "comma-separated candidate names to re-gate instead of all 6 "
            "(xs_momentum,lf_trend,funding_carry,pairs_statarb,vol_breakout,"
            "baseline_rsi_ema). Defaults to all 6."
        ),
    )
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.INFO, format="%(levelname)s %(name)s: %(message)s"
    )

    if args.date:
        day = datetime.strptime(args.date, "%Y-%m-%d").replace(tzinfo=timezone.utc)
        now_ms = int(day.timestamp() * 1000)
    else:
        now_ms = int(time.time() * 1000)

    date_str = date_str_from_ms(now_ms)
    data_dir = (
        Path(_REPO_ROOT) / args.data_dir
        if not Path(args.data_dir).is_absolute()
        else Path(args.data_dir)
    )
    funding_dir = data_dir / "funding"
    out_dir = (
        Path(_REPO_ROOT) / args.out
        if not Path(args.out).is_absolute()
        else Path(args.out)
    )
    pin_path = (
        Path(_REPO_ROOT) / args.pin
        if not Path(args.pin).is_absolute()
        else Path(args.pin)
    )

    if not args.skip_walkforward_record:
        record_walkforward_baseline_trial(date_str)

    candidates = None
    if args.candidates:
        names = [n.strip() for n in args.candidates.split(",") if n.strip()]
        unknown = [n for n in names if n not in _CANDIDATE_BUNDLE_KEY]
        if unknown:
            raise SystemExit(
                f"--candidates: unknown name(s) {unknown}; known: "
                f"{sorted(_CANDIDATE_BUNDLE_KEY)}"
            )
        candidates = names

    results = run_maker_regate(
        data_dir, pin_path, out_dir, funding_dir, now_ms, candidates
    )
    for candidate, record in results.items():
        logger.info(
            "%s: gate1=%s gate2_passed=%s missed=%s fill_rate=%s",
            candidate,
            record.get("gate1_verdict"),
            record.get("gate2_passed"),
            record.get("missed"),
            record.get("fill_rate"),
        )

    errored = [name for name, rec in results.items() if rec.get("error")]
    if errored:
        logger.error("ERROR verdicts: %s — see the verdict docs", ", ".join(errored))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
